### ISSUE TITLE
this is so random - my unwanted code review lol 

### ISSUE THREAD

**Issue by Saliou1920** [faatound/asefa-parfumerie-website#1]
good job mais pourquoi tu utilises en meme temps tailwind css et un autre fichier css dans styles. Tu peux tout faire avec tailwind css. 

une question: tu fais ce projet pour ton business de parfumerie ou tu veux apprendre next js ? 

Parce que implémenter un site e-commerce  from scratch n'est pas une mince affaire. But anyway good job

Pense aussi à deployer ton site sur vercel, c'est gratuit. Tu pourras le tester en live et le partager.

**Comment by faatound** [comment]
hey , oui tu as raison mais je suis toujours en train d'apprendre tailwind
c'est pour cela .
En fait c'est pour les deux car une fois fini cela me permettra de
digitaliser la prise de commande et de renforcer mes bases en next.
Merci beaucoup pour ton review , j'apprécie

**Comment by faatound** [comment]
hey , oui tu as raison mais je suis toujours en train d'apprendre tailwind c'est pour cela .
En fait c'est pour les deux car une fois fini cela me permettra de digitaliser la prise de commande et de renforcer mes bases en next.
Merci beaucoup pour ton review , j'apprécie

**Comment by Saliou1920** [comment]
Okay 👍 parfait
